server:
  port: 8088


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis
    username: root
    password: 1234

logging:
  level:
    cn.itcast.demo: debug

mybatis: #mybatis的配置文件
  mapper-locations: classpath:mappers/**/*.xml #映射文件的路径
  type-aliases-package: com.leyou.pojo
  configuration:
    map-underscore-to-camel-case: true #开启驼峰扫描

